global:
  ociAuthSecret: oci-credentials     # OCI authentication credentials secret name
  oadbAdminSecret: oadb-admin           # Name of DB Admin secret created earlier
  oadbWalletSecret: oadb-wallet         # Name of wallet secret created earlier
  oadbConnectionSecret: oadb-connection # Name of connection secret created earlier
  mock:
    service: "false"


    
